import type { Metadata } from 'next'
import './globals.css'

interface Props {
	children: React.ReactNode
}

const Layout = ({ children }: Props) => {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	)
}

export default Layout

//→ metadata

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
